### ISSUE TITLE
Name mangling for type imports

### ISSUE THREAD

**Issue by titzer** [WebAssembly/gc#231] opened 2021-07-27 19:17 UTC
In the context of today's discussion, a question arose on how a centralized module or loader for coordinating structural type definitions can make use of name mangling to express parameterized (i.e. generic types).

While parameterized types seem like an advanced feature beyond the scope of MVP, even simple languages contain some parameterizable type constructors. E.g. in Java, the array type constructor, and in Go, the `map` type constructor. Therefore the issue is germane to current discusions.

Let's take an example. Suppose we have a Java program that defines a class `A` and uses an array type `A[]`. Suppose, for the sake of example, that the class `A` is private to the program, e.g. it is package-scoped or even private. Consider five scenarios for the generated wasm module.

* The module imports the type `A` and `A[]` and includes "instructions" to the central Java runtime system on how to construct `A`--i.e. which fields and methods it has.
* The module imports the type `A` and `A[]` and defines their (lowered) structure in an auxiliary module.
* The module imports the type `A` and defines it in the auxiliary module, but imports only `A[]`, leaving its definition up to the Java runtime system.
* The module defines the type `A` and `A[]` and uses them internally, not exposing them.
* The module defines the type `A` internally and imports the type `A[]`.

Several of these scenarios could rely on name mangling to refer to the type `A[]`. E.g. we could write the string `"[A"` (which happens to be the JVM's internal mangling scheme) as the name of an imported type. No problem, except that the Java runtime system needs to implement actual logic to parse the mangled name, and potentially generate the array class definition internally. However, name mangling is not sufficient in the last scenario, as the module does not provide the definition of the class to the Java runtime system, and there is *no* name that it can supply in an import that the Java runtime system can identify by name.

To give things names that don't have names, we could try to *export* them, thereby giving them a name. Then name mangling works...except that imports, internal definitions, and exports are no longer topologically sorted (because of the current restriction on section order). This requires relaxing section order.

One could argue that this is not a problem for Java, if we force all Java types to have actual names that are known to the runtime system. However, it poses a problem to other languages or modules from languages that want to offer truly parameterizable modules. To see this, just imagine a language-independent `Vector<T>` wasm module that should be usable by any language. We'd like to allow `Vector<T>` to be instantiated with any type, including wasm types, for which there are not Java, or any other language, names.

Now suppose that we have an additional parameterization mechanism that enables generics. This can be done with type imports to modules or alternatively what @rossberg called "import parameters" in today's presentation (previously, I implemented this in the Wizard engine and used them for Jawa). This allows a module to import a module parameterized by a type, without ever referring to it by name.

In the limit, name mangling to accomplish type (or any other kind of) parameterization requires that all the entitities (types, functions, memories, other exportable things) that could be supplied as arguments to parameterizable things be encodable as strings. That includes basic wasm types like the primitives, but also compound Wasm types like functions and eventually structs and arrays. Then it also requires decoding logic for all those parameterizable things. But there is already a string encoding for such things! It's the binary format. This is why we should instead prefer parameterization of things by wasm things by having a wasm mechanism to do so, rather than reinventing an encoding mechanism at a level up.

FWIW the import arguments mechanism, and relaxing section order, that I discussed in the context of Jawa does exactly this; all imports can be supplied anything that can be exportable, including functions, types, memories, etc. In discussions with @rossberg and @lukewagner, this could be viewed as a type of shorthand for module linking. I would argue that import arguments are simpler and easier to understand, but sticking to the topic at hand, I think it's clear that name mangling is a kludge for the ability to parameterize properly.

**Comment by RossTate** [comment] 2021-07-27 21:03
Based on prior discussions, my understanding was that today's discussion was in the context of no generics (for example, when I raised the concern of forwards compatibility with generics, I was told that was out of scope). If we're not considering generics, then Java has only a few array types at the wasm level (one for each primitive type, and one for reference types in general), all of which can be imported from the central "runtime" module. If we are considering generics, then one can import the nominal type *constructor* for Java arrays of reference types from the central "runtime" module, and then apply that imported constructor with the (imported) type for `A` to denote `A[]`. Or one could ship their module along with an `[A` module that defines the low-level encoding of the `A[]` type, which would then be deduped if another `[A` module also existed (which would avoid the need for the loader to interpret the string `[A`).

Note, also, that we're not suggesting that string mangling should be the preferred solution in all settings. We're just indicating that even in settings where strings are the only things that can be used to connect imports and exports, you can still use string-mangling to get the functionality of structural types using just nominal types.

**Comment by conrad-watt** [comment] 2021-07-27 21:50
My personal opinion is that we should severely limit the amount of time we spend discussing generics as a post-MVP extension to the Wasm type system, especially as a solution to redundant casts. We spent well over half a year on the subject previously, to the exclusion of other topics, with very little to show for it.

We still need to understand how we must compile source-level (and in particular, reified) generics in a given MVP design, even if the answer has to be "casts everywhere and we'll figure out a more efficient scheme/type system extension later". For performance reasons, it may well make sense to investigate a Wasm-level covariant array type (with dynamic store check) as a close-to-MVP feature.

I'll need to spend more time thinking to understand this OP properly (my not-at-all-thought-out knee-jerk take-away is that short of language-independent type-parameterised modules, name mangling appears to work), but I just wanted to get some high level thoughts out immediately.

**Comment by fgmccabe** [comment] 2021-07-27 22:16
Ben raised an interesting conundrum: if a type is supposed to be private, how can it be reified into another type that belongs to another scope? Generally, private types do not seem consistent with structural types. (You might suggest some form of 'cover' for the private type like a sized opaque region. But that is still not truly private: an observer knows it exists even if they are not able to see inside it.)

**Comment by rossberg** [comment] 2021-07-28 07:07
@fgmccabe:
> Generally, private types do not seem consistent with structural types. (You might suggest some form of 'cover' for the private type like a sized opaque region. But that is still not truly private: an observer knows it exists even if they are not able to see inside it.)

Not sure what exactly you are referring to as "private types", but I think that's not correct as a general conclusion, nor in the context of Wasm types.

The kind of privacy I think the OP is referring to is (or should be) orthogonal to structural vs nominal. It simply means that the name of a type (and anything using it) is not visible or accessible outside a certain scope. If that's the case then it doesn't matter if somebody can peek at its definition – they can't get hold of a value (not that all languages get that right...).

Type abstraction (a different privacy mechanism) also is orthogonal to structural vs nominal (at least if you don't have structural casting capabilities on abstract types). It means that the _definition_ of a type is not visible or accessible outside a certain scope. Inside its defining scope, it's totally fine if an abstract type is structurally equivalent to another. That is e.g. the case with ML or similar module systems, where you can happily abstract any structural type.

But most importantly, source language abstraction and privacy mechanisms are largely irrelevant to Wasm-level types. The role of the Wasm type system is to define data representations. It is not its role to protect source-level abstractions! When you compile to linear memory, there is no such protection either. Where needed, it's the producer's responsibility to implement any necessary runtime protection mechanism.

There are cross-language use cases where Wasm-level protection may be desirable. That's what the "private types" suggested in type import proposal provide, though their use case lies more in the same realm as interface types.

**Comment by RossTate** [comment] 2021-07-28 12:32
@fgmccabe is right that @rossberg's approach has major issues with data encapsulation. There is already a thread on this, so I will point out to the group that I have discussed this issue with other experts on module theory and so far they have all found his approach to be problematic. They identified the same composability, extensibility, expressiveness, and performance issues that I identified. (For example, @rossberg's paper on this topic is for a language without subtyping and without private fields.) Most concerningly was that @rossberg's design lets you break *other* module's abstractions (i.e. you can't opt in). @lukewagner has a whole presentation on problems caused by this (though should be aware that some of the possible extensions being considered are problematic with @rossberg's patch). I also spoke with people in TC39 about this, who had expressed surprise about this when it came up during a presentation, and they pointed out similar problems as well as highlighted that strongly encapsulated private fields are being added to JavaScript because they *have* seen that people *do* perform these hacks to get at stuff they shouldn't be (for good and bad reasons). Unlike @rossberg's patch, their approach doesn't require dynamic wrapping, is extensible, and does work well with subtyping/casting. Given that languages like Java/Kotlin/C# would be able to compile to JS and get strongly encapsulated private fields, I feel like WebAssembly should offer the same. (Also, the comparison with linear memory seems to forget that linear memory is inherently unsound. People generally *don't* like that distinct libraries can mess with each other's memory, and one of the traditional benefits of type-safe languages is that you're guaranteed this can't happen.)

**Comment by RossTate** [comment] 2021-07-28 12:37
(Also, this is off topic for this thread. Hopefully @conrad-watt can bring the thread back on topic. I'm interested to get his more-in-depth thoughts on string mangling.)

**Comment by rossberg** [comment] 2021-07-28 13:30
@RossTate, please keep in mind what I explained above:

> But most importantly, source language abstraction and privacy mechanisms are largely irrelevant to Wasm-level types. The role of the Wasm type system is to define data representations. It is not its role to protect source-level abstractions! When you compile to linear memory, there is no such protection either.

So all you're saying, besides being riddled with FUD and misrepresentations, is entirely missing the point that Wasm is not a source language but _a low-level compilation target_. It never has provided data-level encapsulation, in the same way that native code doesn't. Nor was it intended to. Such mechanisms would only be relevant on a layer like interface types, e.g., for representing resources.

You are correct about this being off-topic.

**Comment by tlively** [comment] 2022-02-16 23:45
Closing this because we've settled on a structural type system and chosen not to include type imports in the MVP.

**Closed by tlively** 2022-02-16 23:45 UTC
