### ISSUE TITLE
GC should be dependent on FinalizationRegistry?

### ISSUE THREAD

**Issue by carlopi** [WebAssembly/gc#104] opened 2020-07-15 07:26 UTC
FinalizationRegistry made it's way into V8 and SpiderMonkey: https://caniuse.com/#feat=mdn-javascript_builtins_finalizationregistry.

Would make WebAssembly GC proposal depend on the FinalizationRegistry ease some of the problems at the JS/Wasm boundary?
I was checking the notes (not yet merged: https://github.com/WebAssembly/meetings/blob/gc-07-14-notes/gc/2020/GC-07-14.md) of the 14th meeting and there are some mention of WeakRefs but none of FinalizationRegistry, that would solve at least some of the issues cited there.

**Comment by jakobkummerow** [comment] 2020-07-15 10:21
A few clarifications:

Firstly, that meeting was specifically about "linear memory GC", which is a somewhat confusing term expressing the notion of potential additions to Wasm to help support the use case where a module wants to ship its own GC to manage its own linear memory. That is a distinct approach from the current GC proposal (which is about adding managed objects outside the linear memory, specifically so that modules _don't_ need to ship their own GC, and doesn't run into any of the issues discussed yesterday).

Secondly, yes, JavaScript weak references including the finalization registry can address some of the issues that occur in a system with two independently managed memory "worlds". I think the fact that "FinalizationRegistry" wasn't mentioned by name doesn't indicate that folks weren't aware that JS weakrefs support finalizers.

Thirdly, while the browser embedding is an important use case for Wasm, it's not the only supported scenario, so Wasm can't depend on _any_ JavaScript feature. That said, of course JS features can be used in the Wasm-JS-API, as well as by Web applications that include a Wasm component.

**Comment by carlopi** [comment] 2020-07-15 11:06
Thank you for the answers to both issues.

After having posted the issues I put some more thoughts + a couple of interesting conversations into it, and I strongly suspect a "linear memory GC" (in the Web) could be implemented on top of FinalizationRegistry with the currently available WebAssembly+JS features.
Hopefully in the next weeks I can work a bit on getting a prototype done, I would be curious of having to evaluate how costly it is on the performance side.

As for non-Web embedding, I get that WebAssembly has to live without JavaScript as a host, but say something based on JS WeakRef is workable (and in the near future), then one could also think of creating the necessary opcodes and then having every host implement the FinalizationRegistry equivalent.

**Comment by jakobkummerow** [comment] 2020-07-15 12:06
As I said, weak references and finalizers certainly solve some problems, but they don't solve everything.

> I strongly suspect a "linear memory GC" (in the Web) could be implemented on top of FinalizationRegistry with the currently available WebAssembly+JS features.

I don't think that's possible. You can handle some situations, sure, but you can't free cycles. In the simplest case, imagine a JavaScript object and an "object" in Wasm linear memory, where 
(1) the JS object has a reference to the Wasm object (in whatever format the Wasm module exposed it, maybe an index into that memory, or some other identifier represented as a Number, think "object #17", and the module knows what that means),
(2) the Wasm object has a reference to the JS object (likely via an `externref` in some global or table, which the linear-memory object either hardcodes or stores some identifier of, e.g. table slot index)
(3) both of these objects have fulfilled their respective purposes, nothing else holds references to either of them, so they _should_ get collected now (including deleting/nulling the `externref` wherever it may be stored).

The host-provided JavaScript GC will treat that object as alive (because it sees that there's an `externref` referring to it), and whatever custom GC the Wasm module might bring along must keep the object in its linear memory along with the `externref` alive (because, not having been told otherwise, it must assume that the JS object referring to it is still around). Weak references or finalizers of any kind don't help here, because both objects (as long as they were still useful) required strong references to the other. You could add manual "free this object/reference now!" calls, but then it wouldn't be an automatic GC any more.

The whole "do we want to do anything for linear-memory GCs, and if so, what?" discussion precisely centers around adding primitives of some sort that would make it possible to resolve such cycles. There are established solutions how this kind of thing can be done, so it's certainly a solveable problem, we would only have to select a concrete design. A concern is that existing systems where this problem has been solved before (e.g. the JavaScript <-> DOM interaction in many browsers, but I'm sure there are other, non-Web examples too) often haven't been very happy with these solutions, e.g. because they tended to be brittle (prone to bugs) and inefficient (cases do happen in practice where several expensive GC runs in both worlds are necessary in order to free up some convoluted reference cycle).

**Comment by carlopi** [comment] 2020-07-15 15:50
The solution I was thinking is a bit involved but would be roughly the following:

Every garbage-collectible-linear-memory object would have a JSHandle object that would contain its linear_memory_address and would (upon call of the finalizer) free the memory associated with the object.

Then there would be 3 JS functions imported from each module:
int createHandle(int linear_memory_addres) and
int assignHandle(int linear_memory_address)
this at every invocation would be either creating a JS handle(by createHandle called on construction) or retriving it(assignHandle), getting a unique_identifier, insert in a JS Map map[unique_identifier] = the JSHandle, and return unique_identifier.
Then there would be a function releaseHandle(int unique_identifier) that would remove unique_identifier from the map (+ ideally putting the unique_identifier in a stack of reusable handles.

Then on the wasm side every pointer to one of this special garbage collectible items would need to call createHandle/assignHandle on assigment and releaseHandle on destruction.

Then the JSHandle of a given garbage-collectible-linear-memory object would be just a regular JS object, that would be referenced N times inside the map popolated by assignHandle, and whenever N goes to zero it would be available for GC (and the finalizer would the be called freeing the linear memory).

JS objects that want to reference to the gc-linear-memory items would just need to point to the relevant JSHandle (obtained also through assignHandle) and get from there the linear_memory_address.

All the infrastructure could implemented either on the JS side on the Wasm VM through intrinsics, and doing that JS side would be a way of prototyping / benchmarking this solution.

**Comment by RossTate** [comment] 2020-07-15 17:51
The problem is not collecting the garbage; the problem is determining what is garbage. To determine that, and in particular to identify cycles, the host's GC not only needs to know what linear addresses are conceptually garbage-collectible items, it also needs to know how these items point to each other. So you'd have to extend your proposal with "add_reference_to" and "remove_reference_to" every time a linear-memory slot corresponding to a reference field of one of these conceptual garbage-collectible items is updated. In other words, you essentially maintain a points-to graph in JavaScript, which you fill with finalizers so that the when the host cleans up part of that graph you know to clean up the corresponding items in your linear memory. This works, but unfortunately is intractably expensive, at least as a fine-grained solution. That said, it might work well as a coarse-grained solution for certain applications.

**Comment by carlopi** [comment] 2020-07-15 18:35
I knew I had forgot something out. Yes, there has also to be a mechanism in place to add dependencies to the handles. Thanks for pointing this out / the feedback.
What I would see as an advantage of a similar solution is that can be experimented on top of existing capabilities, and get a performance boost in a future in which this pass from being arbitrary imported function to standard feature that the backing VM can optimize.
I get also the "intractably expensive" part, I might have to rethink whether it's a worthwhile experiment to be carried out.

**Comment by tlively** [comment] 2022-02-23 00:15
Closing this because the original question has been answered. It would still be interesting to see a GC system based on linear memory Wasm, but that would be an alternative to this proposal, not a replacement for it.

**Closed by tlively** 2022-02-23 00:15 UTC

**Comment by carlopi** [comment] 2022-02-23 07:29
Sure, I left it hanging but it had to be closed.
This was mostly a though experiment on the fact that using (in a somehow unconventional way) existing pieces it was somehow possible to simulate proper GC.
